/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;

//import com.google.common.annotations.VisibleForTesting;

import static org.junit.jupiter.api.Assertions.*;

    class AppTest {
        @Test void appHasAGreeting() {
            App classUnderTest = new App();
            assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        }

    @Test 
    void appSuma() {
        App miclase = new App ();
        assertEquals (5, miclase.sumar(3, 2));
        assertEquals (6, miclase.sumar(4, 2));
        assertEquals (7, miclase.sumar(5, 2));
        assertEquals (5, miclase.sumar(3, 2));
        assertEquals (8, miclase.sumar(6, 2));
        assertNotEquals (9, miclase.sumar(6, 2));
    }
    @Test
    void appLengthVaBienConString() {
        App app = new App ();
        assertEquals(3, app.length("hola"));
    }
}
